# Generated by Django 2.2.15 on 2020-08-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvrow',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cvrow',
            name='section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cvrow',
            name='subtitle',
            field=models.TextField(default=''),
        ),
    ]
