# Generated by Django 2.2.15 on 2020-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200831_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvrow',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cvrow',
            name='subtitle',
            field=models.TextField(blank=True, default=''),
        ),
    ]
